### ISSUE TITLE
Come bacc

### ISSUE THREAD

**Issue by sTiKyt** [NitMrAnderson/Terminator-Framework#1]
Ну и зачем ты телегу удалил? Возвращайся давай

**Comment by NitMrAnderson** [comment]
неожидал)

Хорошо, сейчас, буду)

**Comment by sTiKyt** [comment]
> неожидал)
> 
> Хорошо, сейчас, буду)

ну и где?

**Comment by sTiKyt** [comment]
та удали issue, гений, зачем ты его закрыл...
